[package]
name = "grrs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
anyhow = "1.0"
log = "0.4"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "2.0"
assert_fs = "1.0"
